@startmindmap
* Риск:И
	*  Крит-:ИЛИ
		* CI:5
		* MC:4
		* BC:3
		* BO:2
		* OP:1
		* null:0
	* Конф-:ИЛИ
		* СК:3
		* К:2
		* прочее (не СК и не К):1 
		* null:0
	* ИОД-:ИЛИ
		* ТС и ПД:3 
		* ТС:2
		* ПД:2
		* прочее (не ТС и не ПД):1
		* null:0 
@endmindmap